import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "index",
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      items: [
        "getting-started/index",
        "getting-started/installation",
        "getting-started/quick-start",
        "getting-started/provider-setup",
        "getting-started/environment-variables",
        {
          type: "category",
          label: "Providers",
          collapsed: true,
          items: [
            "getting-started/providers/index",
            "getting-started/providers/google-ai",
            "getting-started/providers/google-vertex",
            "getting-started/providers/aws-bedrock",
            "getting-started/providers/azure-openai",
            "getting-started/providers/mistral",
            "getting-started/providers/huggingface",
            "getting-started/providers/ollama",
            "getting-started/providers/litellm",
            "getting-started/providers/sagemaker",
            "getting-started/providers/openrouter",
            "getting-started/providers/openai-compatible",
          ],
        },
      ],
    },
    {
      type: "category",
      label: "SDK",
      collapsed: true,
      items: [
        "sdk/index",
        "sdk/api-reference",
        "sdk/custom-tools",
        "sdk/advanced-features",
        "sdk/framework-integration",
        "sdk/nestjs-integration",
      ],
    },
    {
      type: "category",
      label: "CLI",
      items: ["cli/index", "cli/commands", "cli/examples", "cli/advanced"],
    },
    {
      type: "category",
      label: "Features",
      items: [
        "features/index",
        "features/multimodal",
        "features/structured-output",
        "features/conversation-history",
        "features/hitl",
        "features/guardrails",
        "features/tts",
        "features/audio-input",
        "features/video-generation",
        "features/pdf-support",
        "features/csv-support",
        "features/office-documents",
        "features/real-time-services",
        "features/speech-agents",
        "features/image-generation",
        "features/thinking-configuration",
        "features/regional-streaming",
        "features/provider-orchestration",
        "features/cli-loop-sessions",
        "features/auto-evaluation",
        "features/enterprise-hitl",
        "features/multimodal-chat",
        "features/file-processors",
      ],
    },
    {
      type: "category",
      label: "MCP",
      collapsed: true,
      items: [
        "mcp/overview",
        "mcp/integration",
        "mcp/http-transport",
        "mcp/configuration",
        "mcp/testing",
        "mcp/optimization",
      ],
    },
    {
      type: "category",
      label: "Memory",
      collapsed: true,
      items: ["memory/conversation", "memory/summarization", "memory/mem0"],
    },
    {
      type: "category",
      label: "Workflows",
      collapsed: true,
      items: [
        "workflows/orchestration",
        "workflows/ai-orchestration",
        "workflows/middleware",
        "workflows/custom-middleware",
        "workflows/error-handling",
      ],
    },
    {
      type: "category",
      label: "Observability",
      collapsed: true,
      items: [
        "observability/telemetry",
        "observability/health-monitoring",
        "observability/provider-status",
      ],
    },
    {
      type: "category",
      label: "Deployment",
      collapsed: true,
      items: [
        "deployment/enterprise-proxy",
        "deployment/performance",
        "deployment/performance-guide",
        "deployment/configuration",
        "deployment/configuration-management",
      ],
    },
    {
      type: "category",
      label: "Guides",
      items: [
        "guides/index",
        {
          type: "category",
          label: "Frameworks",
          items: [
            "guides/frameworks/express",
            "guides/frameworks/nextjs",
            "guides/frameworks/fastify",
            "guides/frameworks/sveltekit",
          ],
        },
        {
          type: "category",
          label: "Server Adapters",
          collapsed: false,
          items: [
            "guides/server-adapters/index",
            "guides/server-adapters/hono",
            "guides/server-adapters/express",
            "guides/server-adapters/fastify",
            "guides/server-adapters/koa",
            "guides/server-adapters/security",
            "guides/server-adapters/deployment",
          ],
        },
        {
          type: "category",
          label: "Migration",
          items: [
            "guides/migration/from-langchain",
            "guides/migration/from-vercel-ai-sdk",
          ],
        },
        {
          type: "category",
          label: "Enterprise",
          items: [
            "guides/enterprise/multi-region",
            "guides/enterprise/multi-provider-failover",
            "guides/enterprise/load-balancing",
            "guides/enterprise/cost-optimization",
            "guides/enterprise/monitoring",
            "guides/enterprise/compliance",
            "guides/enterprise/audit-trails",
          ],
        },
        "guides/domain-specific",
        "guides/dynamic-models",
        "guides/session-management",
        "guides/provider-selection",
        "guides/redis-configuration",
        "guides/redis-migration",
        "guides/github-action",
        "guides/migration-guide",
      ],
    },
    {
      type: "category",
      label: "Cookbook",
      collapsed: true,
      items: [
        "cookbook/index",
        "cookbook/batch-processing",
        "cookbook/rate-limit-handling",
        "cookbook/multi-provider-fallback",
        "cookbook/streaming-with-retry",
        "cookbook/error-recovery",
        "cookbook/cost-optimization",
        "cookbook/tool-chaining",
        "cookbook/structured-output",
        "cookbook/conversation-summarization",
        "cookbook/context-window-management",
      ],
    },
    {
      type: "category",
      label: "Tutorials",
      collapsed: true,
      items: [
        "tutorials/index",
        "tutorials/chat-app",
        "tutorials/rag",
        "tutorials/videos",
      ],
    },
    {
      type: "category",
      label: "Examples",
      collapsed: true,
      items: [
        "examples/index",
        "examples/basic-usage",
        "examples/advanced",
        "examples/business",
        "examples/use-cases",
        "examples/mcp-tool-blocking-example",
      ],
    },
    {
      type: "category",
      label: "Reference",
      collapsed: true,
      items: [
        "reference/index",
        "reference/error-codes",
        "reference/troubleshooting",
        "reference/provider-comparison",
        "reference/provider-behavior",
        "reference/provider-feature-compatibility",
        "reference/provider-capabilities-audit",
        "reference/faq",
      ],
    },
    {
      type: "category",
      label: "Development",
      collapsed: true,
      items: [
        "development/index",
        "development/architecture",
        "development/testing",
        "development/testing-plan",
        "development/provider-testing",
        "development/factory-architecture",
        "development/factory-migration",
        "development/large-context-design",
        "development/versioning",
        "development/link-checking",
        "development/changelog-automation",
      ],
    },
    {
      type: "category",
      label: "Community",
      collapsed: true,
      items: [
        "community/contributing",
        "community/code-of-conduct",
        "community/changelog",
      ],
    },
  ],
};

export default sidebars;
